package net.totobirdcreations.looseendslib.util;


import net.minecraft.text.Text;
import net.minecraft.util.Formatting;

public class LooseEndLang {

    public static String getTitle() {
        return "Failed to connect to the server due to mod list conflicts. Please resolve them before joining the server.";
    }
    public static String getClientSuffix() {
        return "This error was generated by your client.";
    }
    public static String getServerSuffix() {
        return "This error was generated by the server.";
    }

    public static String getServerMissing() {
        return "You can not join servers that don't have the following installed:";
    }
    public static String getServerDisallowed() {
        return "You can not join servers that have the following installed:";
    }
    public static String getClientMissing() {
        return "You can not join this server without the following installed:";
    }
    public static String getClientDisallowed() {
        return "You can not join this server with the following installed:";
    }
    public static String getServerInstalledPrefix() {return "Server has ";}
    public static String getClientInstalledPrefix() {return "You have ";}
    public static Text getServerList() {
        return Text.literal("Incompatible mod list").formatted(Formatting.DARK_RED);
    }

}
